name: SwiftUI-Hooks
options:
  bundleIdPrefix: com.ryo.swiftui-hooks
  createIntermediateGroups: true
settingGroups:
  Debug:
    SWIFT_OPTIMIZATION_LEVEL: -Onone
  Release:
    SWIFT_OPTIMIZATION_LEVEL: -O

schemes:
  Hooks:
    build:
      targets:
        Hooks: all
    test:
      targets:
        - Tests

  BasicExample:
    build:
      targets:
        BasicExample: all

  LegacyExample:
    build:
      targets:
        LegacyExample: all

targets:
  Hooks:
    type: framework
    platform: iOS
    sources:
      - Sources
    configFiles:
      Debug: xcconfigs/Hooks.xcconfig
      Release: xcconfigs/Hooks.xcconfig

  Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: Hooks
    configFiles:
      Debug: xcconfigs/Hooks.xcconfig
      Release: xcconfigs/Hooks.xcconfig

  BasicExample:
    type: application
    platform: iOS
    sources:
      - Examples/Basic
    dependencies:
      - target: Hooks
    configFiles:
      Debug: xcconfigs/Example-Basic.xcconfig
      Release: xcconfigs/Example-Basic.xcconfig

  LegacyExample:
    type: application
    platform: iOS
    sources:
      - Examples/Legacy
    dependencies:
      - target: Hooks
    configFiles:
      Debug: xcconfigs/Example-Legacy.xcconfig
      Release: xcconfigs/Example-Legacy.xcconfig
