name: Examples
options:
  bundleIdPrefix: com.ryo.swiftui-hooks-examples
  createIntermediateGroups: true
settingGroups:
  app:
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    CODE_SIGN_STYLE: Manual
    EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
    EXCLUDED_ARCHS[sdk=appletv*]: x86_64
    EXCLUDED_ARCHS[sdk=appletvsimulator*]: arm64

schemes:
  TheMovieDB:
    build:
      targets:
        TheMovieDB: all

  BasicUsage:
    build:
      targets:
        BasicUsage: all

  Todo:
    build:
      targets:
        Todo: all

packages:
  Hooks:
    path: ..

targets:
  TheMovieDB:
    type: application
    platform: iOS
    sources:
      - TheMovieDB
    dependencies:
      - package: Hooks
    deploymentTarget: 14.0
    settings:
      groups:
        - app
      base:
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        TARGETED_DEVICE_FAMILY: 1,2
  BasicUsage:
    type: application
    platform: iOS
    sources:
      - BasicUsage
    dependencies:
      - package: Hooks
    deploymentTarget: 14.0
    settings:
      groups:
        - app
      base:
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        TARGETED_DEVICE_FAMILY: 1,2

  Todo:
    type: application
    platform: iOS
    sources:
      - Todo
    dependencies:
      - package: Hooks
    deploymentTarget: 13.0
    settings:
      groups:
        - app
      base:
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator appletvos appletvsimulator
        TARGETED_DEVICE_FAMILY: 1,2,3
