# https://github.com/actions/virtual-environments

name: GitHub Actions
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Test on macOS
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode_version:
          - "12.4"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
      LEGACY_XCODE_APP: /Applications/Xcode_11.2.1.app
      LEGACY_TARGET_OS: 13.2.2
      LEGACY_RUNTIME_NAME: com.apple.CoreSimulator.SimRuntime.iOS-13-2
      LEGACY_TARGET_DEVICE: iPhone 11 Pro
    steps:
      - uses: actions/checkout@v2
      - name: Show environments
        run: |
          swift --version
          xcodebuild -version
          pod --version

      - name: Podspec lint
        run: pod lib lint Hooks.podspec --allow-warnings --verbose

      - name: Prepare legacy OS simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s $LEGACY_XCODE_APP/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ $LEGACY_TARGET_OS.simruntime
          xcrun simctl list runtimes
          xcrun simctl list devices $LEGACY_TARGET_OS

      - name: Test for macOS
        run: set -o pipefail && xcodebuild build-for-testing test-without-building -scheme Hooks -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Test for iOS
        run: set -o pipefail && xcodebuild build-for-testing test-without-building -scheme Hooks -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Test for tvOS
        run: set -o pipefail && xcodebuild build-for-testing test-without-building -scheme Hooks -configuration Release -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Build for watchOS
        run: set -o pipefail && xcodebuild build -scheme Hooks -configuration Release -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm' ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Build TheMovieDBExample
        run: set -o pipefail && xcodebuild build -scheme TheMovieDBExample -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Build BasicExample
        run: set -o pipefail && xcodebuild build -scheme BasicExample -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Build LegacyExample
        run: set -o pipefail && xcodebuild build -scheme LegacyExample -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=$LEGACY_TARGET_DEVICE,OS=$LEGACY_TARGET_OS" ENABLE_TESTABILITY=YES | xcpretty -c

      - name: Build for Package.swift
        run: set -o pipefail && rm -rf SwiftUI-Hooks.xcodeproj && xcodebuild build -scheme Hooks -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' ENABLE_TESTABILITY=YES | xcpretty -c
